---
title: "About the Dataset and its Source"
---

The dataset used in this project was sourced from Census Bureau Data. If you want to know more about dataset, visit [here](https://data.census.gov/table/ACSST1Y2022.S1901?t=Income%20and%20Poverty&g=040XX00US01,01$0500000&moe=false). The data relates to 20 Counties of Alabama State. The survey was conducted by American Community Survey aka ACS. The data contains 1-year Estimates for 2022 of income and poverty.

The dataset was cleaned before used for analysis. Not all parameters from the dataset was used. Data was picked on selective basis for analysis, only data related to total population, mean income and median income for counties were considered for this project. I have also tried to present the analysis by using income interval from the data with respect to the population of respective counties.

The dataset contains information about 20 counties of 67 total counties in Alabama. May be ACS just conducted survey for 20 States only.

hi